//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Almoxarifado2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Classe
    {
        public int ID_CLAS { get; set; }
        public Nullable<int> ID_SUB_GRU { get; set; }
        public string NOME_CLA { get; set; }
    }
}
